### ISSUE TITLE
ColIterator will cause the columns hidden.

### ISSUE THREAD

**Issue by ofunc** [plandem/xlsx#10]
```
for cols := sheet.Cols(); cols.HasNext(); {
	cols.Next()
}
xl.Save()
```
The columns in the saved file is hidden.

**Comment by plandem** [comment]
It's not clear what is issue - iterator walks through hidden columns or what?

**Comment by ofunc** [comment]
```
	xl, err := xlsx.Open("test.xlsx")
	if err != nil {
		log.Fatal(err)
	}
	defer xl.Close()

	for cols := xl.Sheet(0).Cols(); cols.HasNext(); {
		cols.Next()
	}

	xl.SaveAs("out.xlsx")
```
The column's width is changed(different with the column's width in file test.xlsx) in file out.xlsx. In some case, the column may hidden.

**Comment by plandem** [comment]
can you attach that file? Iterator should not modify any data

**Comment by ofunc** [comment]
```
package main

import (
	"log"

	"github.com/plandem/xlsx"
)

func main() {
	xl, err := xlsx.Open("test.xlsx")
	if err != nil {
		log.Fatal(err)
	}
	defer xl.Close()

	for cols := xl.Sheet(0).Cols(); cols.HasNext(); {
		cols.Next()
	}

	//	xl.Save() ERROR: Access is denied.
	xl.SaveAs("out.xlsx")
}
```
[test.xlsx](https://github.com/plandem/xlsx/files/3088859/test.xlsx)
[out.xlsx](https://github.com/plandem/xlsx/files/3088860/out.xlsx)
![mod](https://user-images.githubusercontent.com/37168484/56277346-c1db1700-6136-11e9-9637-85c44377a988.png)

**Comment by plandem** [comment]
ok, there is a bug/unsupported feature with columns. Will try to fix.

**Comment by plandem** [comment]
I updated columns feature, some bugs removed and also updated functionality. Can you test it now?

**Comment by ofunc** [comment]
It's working as expected now. Thanks!
