### ISSUE TITLE
How do I get the StyleID of cell, row and column?

### ISSUE THREAD

**Issue by ofunc** [plandem/xlsx#11]
In this way, I can set the same style for the new cells, rows and columns as the specified cells, rows and columns.

**Comment by plandem** [comment]
well, right now it's not possible. Idea was to create library for humans, not robots. So  id of style was not supposing to use directly. i started to add more features some time ago, but it still not finished, but it will be possible to use existing styles.

**Comment by ofunc** [comment]
Thank you for your work. I will keep watching this project.

**Comment by plandem** [comment]
I will try finish columns issue today

**Comment by plandem** [comment]
I pushed recent changes that include styles, but that branch is not release ready yet. Its stable (all tests works as before), but some planned features are not added yet, but if it's critical for you, then you can try:

Here is branch:
https://github.com/plandem/xlsx/tree/feature/hyperlink

**Comment by ofunc** [comment]
The Formatting method is what I need. Thank you!

**Comment by plandem** [comment]
That branch was created for hyperlink feature, but during implementation I had to add other features, e.g. full support of merged cells, so don't be fooled with name of branch, it's more like develop right now :) Hope I will have time to finish hyperlink helper type - the only thing that not finished to release it.
