### ISSUE TITLE
Conditional format may lost

### ISSUE THREAD

**Issue by ofunc** [plandem/xlsx#12]
Open a file which has several conditional formats, and then save as a new file. The new file only has the last conditional format, the others conditional formats have been lost.

**Comment by plandem** [comment]
can you attach that file before and after?

**Comment by ofunc** [comment]
```
package main

import (
	"log"

	"github.com/plandem/xlsx"
)

func main() {
	xl, err := xlsx.Open("test.xlsx")
	if err != nil {
		log.Fatal(err)
	}
	defer xl.Close()

	for cols := xl.Sheet(0).Cols(); cols.HasNext(); {
		cols.Next()
	}

	//	xl.Save() ERROR: Access is denied.
	xl.SaveAs("out.xlsx")
}
```
[test.xlsx](https://github.com/plandem/xlsx/files/3119666/test.xlsx)
[out.xlsx](https://github.com/plandem/xlsx/files/3119667/out.xlsx)

**Comment by plandem** [comment]
There is was a bug with xlsx markup
