### ISSUE TITLE
The correct way to get sheets based on name.

### ISSUE THREAD

**Issue by ofunc** [plandem/xlsx#15]
I'm doing it now in the following way:
```go
for i, v := range spreadsheet.GetSheetNames() {
	if v == name {
		return spreadsheet.Sheet(i)
	}
}
return nil
```
But I'm not sure it's right in all cases.

**Comment by plandem** [comment]
yep, I worked with excelize and getting sheet by name was annoying, because in my case it was not possible to know name of sheet - customer could rename it, but index was static.

I can add ```SheetByName``` method, but under the hood it will be very close to your way

**Comment by plandem** [comment]
```SheetByName``` was added, also conditional formatting is 100% support and in proper human friendly way to use, you can check README.md


p.s.: right now, only ```develop``` branch that has broken backward compatibility - some methods were renamed
