### ISSUE TITLE
 undefined: ml.Name

### ISSUE THREAD

**Issue by tegk** [plandem/xlsx#18]
go/src/github.com/plandem/xlsx/internal/ml/shared_strings.go:10:14: undefined: ml.Name

There is RIDName but no Name.

**Comment by plandem** [comment]
what branches do you use? it was recent change in ooxml package

**Comment by plandem** [comment]
Ok, I forgot to push reverted changes in master. It should work right now. Sorry.

**Comment by plandem** [comment]
There will be 1.0 release really soon with some breaking changes - few methods will be renamed. ```develop``` is really close to that release, just missing last feature that im working right now - comments feature.
