### ISSUE TITLE
Fastest way to load huge data?

### ISSUE THREAD

**Issue by tegk** [plandem/xlsx#19]
What would be the fastest method to load huge files? Concurrency and streaming possible?

**Comment by plandem** [comment]
How huge? But anyway
1) Open sheet in stream mode
```
	xl, err := xlsx.Open(....)
	if err != nil {
		panic(err)
	}

	//open as read-stream and after as read-write
	sheet = xl.Sheet(0, xlsx.SheetModeStream)
	defer sheet.Close()
```
2) Concurrency is not supported right now


P.S.: stream mode has limited features set

**Comment by tegk** [comment]
Basically I am trying to parse a file with 1 million lines as fast as possible. I am happy to contribute some code. What kind of approaches would you consider to speed up working with big files?

**Comment by plandem** [comment]
Well, with huge files we have 2 issues: a) speed and b) memory

For (a) Open sheet in stream mode is fastest way right now and no real way to optimize it except  checking closely with debugger/profiler to get ideas which methods can be improved. 

For (b) unzip file on disk before opening. But that way will require some core changes, so till majority features implemented, that task has lowest priority.

**Comment by plandem** [comment]
about concurrency - it will not help to speedup. When I said that concurrency is not supported, I meant that it's not safe to use in concurrency model - from different threads, library has not any locking/unlocking features.

**Comment by tegk** [comment]
Do you think that reading in stream mode concurrently would speed up the loading processes?
