### ISSUE TITLE
InsertRow (for sheetReadWrite)

### ISSUE THREAD

**Issue by silviucm** [plandem/xlsx#2]
Hi,

Given the following example: https://play.golang.org/p/G6QwfVo8CFb 
which instantiates a new doc, with a blank new sheet, my expectation when invoking InsertRow twice with index 0 was the first two rows being populated with the text.

It appears that the cell pointers are still somehow pegged to the old row: the text appears on the 3rd row.

Please advise if the approach is incorrect, and another approach is necessary when creating documents from scratch (maybe an example in the readme).

Cheers,
silviu

**Comment by plandem** [comment]
Hi.

Thanks for report. Looks like InsertRow had a bug, exactly like you wrote - pointer for row was same. InsertCol was working as expected. My tests somehow worked, but I added more tests to be sure. Now everything is working as supposed.

Btw, I also added method Cell() to Row and Col. So now it's possible to do:
```go
row := sheet.Row(1)
row.Cell(2).SetValue(1)
```

**Comment by plandem** [comment]
there are more examples here: https://godoc.org/github.com/plandem/xlsx

**Comment by silviucm** [comment]
Hi @plandem - great that seems to have fixed it.

I noticed another issue (not sure if related). Insert this **SetDimension** line just before the first InsertRow call:
```
s.SetDimension(10, 10)  // Net new line (before the first InsertRow)

// Insert a row at index 0
row := s.InsertRow(0)  // This line was already there
```

I am getting an "index out of range" panic at the InsertRow, if SetDimension if called previously:

> panic: runtime error: index out of range
> goroutine 1 [running]:
> github.com/plandem/xlsx.(*sheetReadWrite).expandIfRequired(0xc42000c0d0, 0x0, 0xa)
> 	/home/silviu/projects/go/src/github.com/plandem/xlsx/sheet_readwrite.go:323 +0x80c
> github.com/plandem/xlsx.(*sheetReadWrite).InsertRow(0xc42000c0d0, 0x0, 0xa)
> 	/home/silviu/projects/go/src/github.com/plandem/xlsx/sheet_readwrite.go:81 +0x60
> main.main()
> 	/home/silviu/projects/go/src/various/excel/plandem/main.go:35 +0x211

I didn't want to open another issue. Maybe you can check and fix it within the same issue

Cheers,
silviu

**Comment by plandem** [comment]
hi! You was right again. There was a bug (introduced after adding SheetReader) with SetDimension.  I fixed it now.

**Comment by silviucm** [comment]
good job !
