### ISSUE TITLE
Consider preallocating slice

### ISSUE THREAD

**Issue by tegk** [plandem/xlsx#20]
I noticed when looking for performance optimisation that you could preallocate some slices for better performance.

xlsx/internal/hash/reserved.go:14:2: Consider preallocating `result` (prealloc)
	var result []string

xlsx/internal/ml/primitives/bounds_list.go:12:2: Consider preallocating `list` (prealloc)
	var list []Bounds
	^
xlsx/internal/ml/primitives/bounds_list.go:28:2: Consider preallocating `refs` (prealloc)
	var refs []string

Read more here:
https://github.com/alexkohler/prealloc

**Comment by plandem** [comment]
Hi, will check. `Bounds` is using heavily, so can impact. Thanks

**Comment by plandem** [comment]
will be in next update
