### ISSUE TITLE
Доступ к NewRange 

### ISSUE THREAD

**Issue by trueone** [plandem/xlsx#25]
Привет, что если бы была функция которая возвращает Range, как ты на это смотришь?
Если все ок, могу кинуть PR

```
//Range is a object that provides some functionality for cells inside of range. E.g.: A1:D12
type Range struct {
	//we don't want to pollute Range with bound's public properties
	bounds types.Bounds
	sheet  Sheet
}

//NewRange create and returns Range by bounds [see types.BoundsFromIndexes()] and sheet interface
func NewRange(bounds types.Bounds, sheet Sheet) *Range {
	return &Range{
		bounds,
		sheet,
	}
}
```

Я тут пишу обертку над твоей либой, было бы удобно объединять ячейки зная только индексы строк и столбцов

**Comment by plandem** [comment]
Привет. такая функция есть, но она "приватная":
```
func newRange(sheet Sheet, fromCol, toCol, fromRow, toRow int) *Range
```
А для чего эта функция?

Для объединения же есть:
```
MergeRows
MergeCols
```

Или ты про то, что сейчас нет возможности получить Range через индексы? Хорошая мысль, так как ячейки можно и по индексу и по Ref получить. Возможно для Range тоже разумно было бы. Скорее всего добавлю новый метод, а текущей переименую
```
Range(fromCol, fromRow, toCol, toRow)
RangeByRef(r Ref)
```

**Comment by trueone** [comment]
Дело в том что `MergeRows` и `MergeCols` объединяют все строки\столбцы (что странно)

Да, я как раз про то чтобы получать Range через индексы.
`
Range(fromCol, fromRow, toCol, toRow)
RangeByRef(r Ref) //текущий
`
Это отличный вариант, буду благодарен если сделаешь)

Хотя.. видимо я могу использовать эту часть кода для моих целей
`
s.Range(types.RefFromCellRefs(
		types.CellRefFromIndexes(fromIndex, 0),
		types.CellRefFromIndexes(toIndex, internal.ExcelRowLimit),
	)).Merge()
`
Да, сорри, RefFromCellRefs решает мои проблемы, спасибо!)
