### ISSUE TITLE
Border

### ISSUE THREAD

**Issue by veliev** [plandem/xlsx#26]
Thanks for the work you've done. Tell me how to work with borders and center alignment.

**Comment by plandem** [comment]
Hi, looks like need more examples. You can check `style_test.go` in `format/styles` package
```
	st := xl.AddStyles(
		styles.New(
			//alignment
			Alignment.VAlign(VAlignBottom),
			Alignment.HAlign(HAlignFill),
			//full border
			Border.Type(BorderStyleDashDot),
			Border.Color("#FF00FF"),
			//partial borders
			Border.Diagonal.Type(BorderStyleDashDot),
			Border.Diagonal.Color("#FF00FF"),
			Border.Vertical.Type(BorderStyleDashDot),
			Border.Vertical.Color("#FF00FF"),
			Border.Horizontal.Type(BorderStyleDashDot),
			Border.Horizontal.Color("#FF00FF"),
		)
	)
```

**Comment by veliev** [comment]
@plandem Thanks!!!

**Comment by veliev** [comment]
Tell me, is it possible with the help of your library xlsx in other formats?

**Comment by plandem** [comment]
nope, only xlsx

**Comment by veliev** [comment]
@plandem is it possible to change the sheet parameters, such as  Zoom, FitToPagesWide, FitToPagesTall?

**Comment by plandem** [comment]
it's not possible right now
