### ISSUE TITLE
cannot using in project with govendor

### ISSUE THREAD

**Issue by LucienLS** [plandem/xlsx#33]
when my project using govendor to manage golang packages, xlsx2go package cannot compile correctly, the "go:linkname" compile have error, the error belows:
(can you remove the go:linkname in the package?)

liushun.lucien/own_study/vendor/github.com/plandem/xlsx/format/conditional.(*Info).Validate: relocation target github.com/plandem/xlsx/format/conditional/rule.fromRule not defined
liushun.lucien/own_study/vendor/github.com/plandem/xlsx/format/conditional.AddRule.func1: relocation target github.com/plandem/xlsx/format/conditional/rule.fromRule not defined
liushun.lucien/own_study/vendor/github.com/plandem/xlsx.(*conditionals).Add: relocation target github.com/plandem/xlsx/format/conditional.from not defined
liushun.lucien/own_study/vendor/github.com/plandem/xlsx.(*hyperlinks).Add: relocation target github.com/plandem/xlsx/types/hyperlink.from not defined
liushun.lucien/own_study/vendor/github.com/plandem/xlsx.toRichText: relocation target github.com/plandem/xlsx/format/styles.toRichFont not defined
liushun.lucien/own_study/vendor/github.com/plandem/xlsx.(*styleSheet).addDiffStyle: relocation target github.com/plandem/xlsx/format/styles.from not defined
liushun.lucien/own_study/vendor/github.com/plandem/xlsx.(*styleSheet).addStyle: relocation target github.com/plandem/xlsx/format/styles.from not defined

**Comment by plandem** [comment]
Could you make it work?

**Comment by LucienLS** [comment]
I try to solve the problem, and make a pull request 
[link](https://github.com/plandem/xlsx2go/pull/36)

**Comment by plandem** [comment]
I renamed project in github from xlsx2go back to xlsx. So no redirection right now. Can you check if it works with govendor or now?!

**Comment by LucienLS** [comment]
Yes, it can work with govendor now, it's great

**Comment by plandem** [comment]
Got you. Sad, but looks like renaming repository was bad idea. Not every vendoring tool supports redirections
