### ISSUE TITLE
sheet corrupted after save

### ISSUE THREAD

**Issue by shaunc** [plandem/xlsx#38]
While working on https://github.com/plandem/xlsx/issues/37, I tried to open a truncated version of an example spreadsheet in "not streaming" mode to make my modifications.

Here is the original sheet:

[mfi101119holdingslist_100_noissuer.xlsx](https://github.com/plandem/xlsx/files/3800025/mfi101119holdingslist_100_noissuer.xlsx)

The goal is to lookup matches for the "issuer" column in a database of previous entries and select the best match.

To this end I iterate though the sheet using `row = rows.Next()` collect some fields to use in a database query, then use 
```go
cell := match.Row.Cell(mi.IColIssuer)
// everything output by this diagnostic is reasonble
fmt.Println("I", match.Row.Bounds(), mi.IColIssuer, match.Issuer)
cell.SetText(match.Issuer)
```
to write the data (`match.Issuer` is of type string).
Finally I save the data; it doesn't seem to be documented whether to call save before or after sheet.Close() so I tried both ways:
```go
sheet.Close()
xl.SaveAs("./foo.xlsx") // also tried this first
xl.Close()
```
The resulting file is corrupt:
[foo.xlsx](https://github.com/plandem/xlsx/files/3800045/foo.xlsx)

**Comment by plandem** [comment]
let me check what's wrong with file...hadn't any corrupted for ages

**Comment by shaunc** [comment]
Thank you  ... I'm sure I could have done something wrong. :) ... But also perhaps update via iterator isn't well tested? (PS -- save after sheet close is presumably correct? ... how does that work with streaming write? If I do save as after write but there are other sheets, they are all copied, I presume? ... might be good to document somewhere.)

**Comment by plandem** [comment]
Actually I found a bug in markup - that's a reason for corrupted file. Looks like it's relatively new bug, because I had tested library against your file (not exactly your, but same **mfi** file) and it worked well in the past. Get v1.0.4

**Update:** Actually looks like that bug was introduced quite long time ago. But since it's related to **not implemented** feature it was hard to track. Thanks again for report.

**Comment by plandem** [comment]
regarding to **Close** for sheet, well...right now it's used by read in stream mode only. For other cases it has no any code under the hood.

**Comment by shaunc** [comment]
Great -- thanks!

I'm the person they go to to automate things, but the rest of the company are excel natives; my mandate is to make things easier for them but not disturb their workflows unnecessarily. They like putting complex features into excel, so they are a good source of challenging spreadsheets for you. (Just wait until I try to automate sheets with pivot tables... :))

... but if you have a chance later in the weekend -- I would really be grateful for your further thoughts on the "sed-mode" update.

**Comment by plandem** [comment]
complex files to test is totally fine. That's a reason why that library was born. I was in your shoes - some managers of client used heavy (like really heavy) formatted excel as the source of truth, but the same time they wanted to add some **auto diff** feature to compare reports for two months and mark in later one changed rows with keeping all that formatting.

**Comment by shaunc** [comment]
Great -- can confirm that it writes!

NB I get the following message (still) when I open. Is there anything internal to the sheet that says someone is using it? This could be related to fact that I am running in macOS and opening spreadsheet in windows running in parallels.

![image](https://user-images.githubusercontent.com/193170/68074955-d94abc00-fd77-11e9-8c6f-d6269b1ecae9.png)

**Comment by plandem** [comment]
probably because of parallels. I test everything in OSX.
