### ISSUE TITLE
Make `sheetMode` public

### ISSUE THREAD

**Issue by shaunc** [plandem/xlsx#39]
I would like to do something like:
```go
var flags xlsx.SheetMode 
if !save {
  flags = xlsx.SheetModeStream
}
...
[perhaps elsewhere...]
...
sheet := xl.Sheet(0, flags)
```
But:
* `sheetMode` can't be referenced
* nice to have a name for the "default mode" (`SheetModeUnknown`?) available.

Of course there are other ways to do this, but it would seem a trivial change to the package that would allow more idiomatic code.

**Comment by plandem** [comment]
Well, don't forget that we have Sheet() to open and AddSheet() to create. But probably need to make **sheetMode** public, not **sheetModeUnknown**.

**Comment by plandem** [comment]
Check v1.0.4 - made SheetMode type public
