### ISSUE TITLE
Unable to use vars (type string) as type types.Ref in argument to sheet.Range

### ISSUE THREAD

**Issue by tomcharter365** [plandem/xlsx#4]
### Description:
I am still new to go and perhaps this is not an issue but more of a lack of understanding on my part.

However, I am unable to use vars (type string) as type types.Ref in argument to sheet.Range when trying to access range by references in A1notation

#### Working code
_This current code works well if range references are known and can be written into the script:_
```
package main

import (
  "fmt"
  "strings"

  "github.com/plandem/xlsx"
)

// declare document
const doc string = "./test_files/example_simple.xlsx"

func main() {
  xl, err := xlsx.Open(doc)
  if err != nil {
    panic(err)
  }
  defer xl.Close()

  // Get sheet by 0-based index
  sheet := xl.Sheet(0)

  // // Get range by references
  area := sheet.Range("D10:H13")
  fmt.Println(strings.Join(area.Values(), ","))
}
```
#### Broken code
_This can allow for changes to the range since the refs are vars but does not work:_
```
package main

import (
  "fmt"
  "strings"

  "github.com/plandem/xlsx"
)

// declare document
const doc string = "./test_files/example_simple.xlsx"

func main() {
  xl, err := xlsx.Open(doc)
  if err != nil {
    panic(err)
  }
  defer xl.Close()

  // Get sheet by 0-based index
  sheet := xl.Sheet(0)

  // // Get range by vars
  var rangeStart string = "D10"
  var rangeEnd string = "H13"
  area := sheet.Range(rangeStart + ":" + rangeEnd)
  fmt.Println(strings.Join(area.Values(), ","))
}
```
#### Error from broken code:
```
.\read-range.go:44:40: cannot use rangeStart + ":" + rangeEnd (type string) as type types.Ref in argument to sheet.Range
```

#### Expected results:
It was expected that both the working code and the broken code would return the same results, however they do not.

#### Output of `go version`:
```
go version go1.11.1 windows/amd64
```
#### xlsx commit id
```
529e812
```

**Comment by plandem** [comment]
Go has strict typing. So you can't use string type directly, because range expects **types.Ref**
```go
import "github.com/plandem/xlsx/types"
...
sheet.Range(types.Ref(rangeStart + ":" + rangeEnd))
```
```

**Comment by plandem** [comment]
I close issue, if you have other question - create a new one.

**Comment by tomcharter365** [comment]
Thank you so much, your package has been extremely helpful.

**Comment by plandem** [comment]
you are welcome :)

you also can create Ref like this:
```go
sheet.Range(types.RefFromCellRefs(rangeStart, rangeEnd))
```
