### ISSUE TITLE
How to retrieve style for existing data

### ISSUE THREAD

**Issue by dougwinsby** [plandem/xlsx#49]
There's good support for **setting** styles, but I'm having trouble **getting** styles for existing data.

I need to see if a cell has bold style, which I believe is in `DiffStyle` accessed by `Info.styleInfo` (not public).

I tried something like this:

```go
styleID := sheet.Cell(c, r).Styles()
styleInfo := xl.ResolveStyles(styleID)
```

But I couldn't access any members of `Info` struct because they are not public. Is there another way to do this?

**Comment by plandem** [comment]
not right now. There was a plan to make Styles() to return real info, instead of ID, but that's it
