### ISSUE TITLE
Error "Index out of range" for some files (excelize can read its)

### ISSUE THREAD

**Issue by vsile** [plandem/xlsx#5]
I run my script
```
package main

import (
    "fmt"
    "github.com/plandem/xlsx"
)

func main() {
    xl, err := xlsx.Open("goserver/mser/go/Аналитика по МКД_clean.xlsx")
    if err != nil {
        panic(err)
    }
    defer xl.Close()
    fmt.Println(xl.GetSheetNames())
    fmt.Println(xl.Sheet(0))
}
```
And get an error:

```
user@c107 ~ $ go run goserver/mser/go/test4.go 
[МКД Организации conf]
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/plandem/xlsx.(*sheetReadWrite).expandOnInit(0xc42000c0f8)
	/home/user/goserver/src/github.com/plandem/xlsx/sheet_readwrite.go:293 +0x601
github.com/plandem/xlsx.(*sheetReadWrite).(github.com/plandem/xlsx.expandOnInit)-fm()
	/home/user/goserver/src/github.com/plandem/xlsx/sheet_readwrite.go:394 +0x2a
github.com/plandem/ooxml.(*PackageFile).LoadIfRequired(0xc4200846e0, 0xc420111eb8)
	/home/user/goserver/src/github.com/plandem/ooxml/package_file.go:88 +0x9a
github.com/plandem/xlsx.(*sheetReadWrite).afterOpen(0xc42000c0f8)
	/home/user/goserver/src/github.com/plandem/xlsx/sheet_readwrite.go:394 +0x54
github.com/plandem/xlsx.(*Spreadsheet).Sheet(0xc420084370, 0x0, 0x1, 0x25)
	/home/user/goserver/src/github.com/plandem/xlsx/spreadsheet.go:63 +0xad
main.main()
	/home/user/goserver/mser/go/test4.go:17 +0x11e
exit status 2
```
What's wrong with [my file](https://yadi.sk/i/sqskFkXxhUczXQ)?

[360EntSecGroup-Skylar/excelize](https://github.com/360EntSecGroup-Skylar/excelize) library reads this file correctly.

**Comment by plandem** [comment]
Файл кривой. Если проверить информацию, то там записано, что размерность первой вкладки A1:AH1, т.е. одна строка всего, но самом деле там тысячи строк. В библиотеку заложено работа с файлами без заданной размерности, но в данном случае размерность задана, но кривая. Я подумаю что можно сделать. Если бы размерности не было, то файл бы открылся нормально.

**Comment by piotrkoper** [comment]
For those using english: the file is corrupted.
You can handle the situation this way:
```
func getSheet(wb *xlsx.Spreadsheet, name string) (file xlsx.Sheet, e error) {
	defer func() {
		if err := recover(); err != nil {
			e = errors.New("File corrupted")
		}
	}()
	for sheets := wb.Sheets(); sheets.HasNext(); {
		_, sh := sheets.Next()
		if sh.Name() == name {
			file = sh
			return
		}
	}
	e = errors.New(name + " sheet not found")
	return

}
```

The 360EntSecGroup-Skylar/excelize handles the file without a problem but to process 30000+ lines and 10+ columns takes ages.
plandem/xlsx is mutch faster.+

**Comment by plandem** [comment]
@piotrkoper original issue is about other - corrupted sheet meta data, like Dimension that was set to wrong number. Library relies on dimension if there is any or auto resolve it if there is no any. I have a solution - just an additional option to open sheet, something like "autoResolveDimension" and use already existing mechanics for it. But right now I'm busy with other features, so that fix/feature is postponed.

**Comment by plandem** [comment]
@vsile Библиотека обновилась, я добавил возможность задать режим игнорирования размерности вкладки.
```
package main

import (
    "fmt"
    "github.com/plandem/xlsx"
)

func main() {
    xl, err := xlsx.Open("goserver/mser/go/Аналитика по МКД_clean.xlsx")
    if err != nil {
        panic(err)
    }
    defer xl.Close()
    fmt.Println(xl.GetSheetNames())
    fmt.Println(xl.Sheet(0, xlsx.SheetModeIgnoreDimension)) // <- use this mode
}
```
