### ISSUE TITLE
Support for ECMAScript module

### ISSUE THREAD

**Issue by mdantonio** [plandem/xlsx#50]
Hello, I'm opening this issue because I did not find other discussions about that, please redirect me on the proper issue if you are already discussing it. I was looking for any solution for the Angular 10 warnings (CommonJS or AMD dependencies can cause optimization bailouts.), rather that simply ignore them by configuring allowedCommonJsDependencies in angular.json.
I realized that a ECMAScript module would be needed to make Angular happy. Is there any plan to build xlsx in that way?

Thank you a lot for the support

**Comment by plandem** [comment]
this library in Go, not in javascript
