### ISSUE TITLE
{header:1} facing issue

### ISSUE THREAD

**Issue by appasaheb4** [plandem/xlsx#53]
Argument of type '{ header: number; }' is not assignable to parameter of type 'Sheet2CSVOpts'.
  Object literal may only specify known properties, and 'header' does not exist in type 'Sheet2CSVOpts'.

```
const data = XLSX.utils.sheet_to_csv(ws,{ header: 1 });
```

**Comment by sasicodes** [comment]
@appasaheb4 Facing the same. Resolved by any chance yourself?

**Comment by plandem** [comment]
@appasaheb4 @sasicodes are you sure that using this library, but not something else?
