### ISSUE TITLE
How to set value without change the style?

### ISSUE THREAD

**Issue by ofunc** [plandem/xlsx#7]
Call cell.SetFloat will change the original style. How to set a float value without change the original style?

**Comment by plandem** [comment]
Sadly, it's not possible right now.  The only solution as I see, make `SetValue` set value without styling, so it will be possible to use general  way, because `SetFloat` is exactly like this - set value and set float style.

**Comment by plandem** [comment]
Will it work for you?
1) if there is no any style, then add style
2) if there is ANY style (event not for that type), then preserve it and update value only?

**Comment by plandem** [comment]
Ok, I made a hot fix, behaviour is as I suggested before - when you set value, if there is any style already, then don't overwrite it

**Comment by ofunc** [comment]
It works, thank you!
