### ISSUE TITLE
Stream write

### ISSUE THREAD

**Issue by trueone** [plandem/xlsx#8]
Hi!

Have u got any examples of stream writing? 
Or this lib has only stream read mode

**Comment by plandem** [comment]
Hi,

Library has no support of stream writing right now. It's possible to extend, but it's not clear how to make it - xlsx is set of files, you can write xml in stream mode, but what about other files - they also can be huge. 

What I mean, without using filesystem as temporarily storage during writing xlsx, I have no idea how to achieve the goal - decrease memory usage.

**Comment by trueone** [comment]
Привет, не заметил что автор русскоязычный)

В мире php есть такая библиотечка github.com/box/spout которая позволяет записывать без увеличения потребления памяти с широкими возможностями в плане стилизации.

Начал искать такой функционал в GO и наткнулся на github.com/teleag, там один из пул реквестов добавил функционал стрим записи. При тестировании которой я обнаружил что если выгружать в стрим режиме большие данные 100 столбцов в 1млн строк, то что-то происходит с самим файлом и эксель при открытии его долго пытается восстановить.

В общем и целом в GO нет такой библиотеки которая мне нужна(
Таск можно закрывать думаю)

**Comment by plandem** [comment]
в tealeg в том реквесте очень все криво и топорно сделано, так я точно делать не буду. посмотрю box/spout. Как я сказал, нужна идея как сделать.

**Comment by plandem** [comment]
посмотрел мельком, как я и думал они используют временную папку для этого. подумаю еще раз как сделать лучше и может придумаю чего.

**Comment by trueone** [comment]
спасибо!
