### ISSUE TITLE
How to save the file correctly?

### ISSUE THREAD

**Issue by ofunc** [plandem/xlsx#9]
If call xl.Save before xl.Close:
`rename 测试.xlsx950735883 测试.xlsx: Access is denied.`

If call xl.Save after xl.Close:
Got a invalid file.

**Comment by plandem** [comment]
``Save``` should be before ```Close```

Saving process looks like - create temp file on disk, save anything, rename temp file to required name. If your file has only read access, then you can't save it. But you can try ```SaveAs``` and use different name.

**Comment by ofunc** [comment]
In Save function: Create a temp file and save everything, then rename temp file to required name. But at this time, the original file is still opened(same filename with the required name), so I'll get an error message: Access is denied. (GOOS=windows, GOARCH=amd64).
An error-free process is like this:
```
xl.SaveAs(tmpname)
xl.Close()
os.Rename(tmpname, requiredname)
```
But this will cause xl closed, which is not expected.

**Comment by plandem** [comment]
Check access rights for file
